
class Test1: { x: int }
//│ Defined class Test1

Test1
//│ res: {x: int & 'x} -> (Test1 with {x: 'x})
//│    = [Function: res]

Test1 { x = 123 }
//│ res: Test1 & {x: 123}
//│    = Test1 { x: 123 }

:e
Test1 { x = "oops" }
//│ ╔══[ERROR] Type mismatch in application:
//│ ║  l.14: 	Test1 { x = "oops" }
//│ ║        	^^^^^^^^^^^^^^^^^^^^
//│ ╟── expression of type `"oops"` does not match type `int`
//│ ║  l.14: 	Test1 { x = "oops" }
//│ ║        	            ^^^^^^
//│ ╟── but it flows into record literal with expected type `{x: ?x}`
//│ ║  l.14: 	Test1 { x = "oops" }
//│ ║        	      ^^^^^^^^^^^^^^
//│ ╟── Note: constraint arises from type reference:
//│ ║  l.2: 	class Test1: { x: int }
//│ ╙──     	                  ^^^
//│ res: error | (Test1 with {x: "oops"})
//│    = Test1 { x: 'oops' }

def Test1 = fun x -> Test1 { x = x }
//│ Test1: (int & 'a) -> (Test1 with {x: 'a})
//│      = [Function: Test11]

class Test11: { x: int }
def Test11 x = Test11 { x }
//│ Defined class Test11
//│ Test11: (int & 'a) -> (Test11 with {x: 'a})
//│       = [Function: Test112]


:e
type Test1 = { x: int }
//│ ╔══[ERROR] Type 'Test1' is already defined.
//│ ║  l.42: 	type Test1 = { x: int }
//│ ╙──      	     ^^^^^

type Test2 = { x: int }
//│ Defined type alias Test2

:pe
class Test = { x: int }
//│ /!\ Parse error: Expected end-of-input:1:12, found "= { x: int" at l.51:12: class Test = { x: int }

:pe
type Test: { x: int }
//│ /!\ Parse error: Expected "=":1:10, found ": { x: int" at l.55:10: type Test: { x: int }

type Test3 = int -> int
//│ Defined type alias Test3

type Test4 = int -> int -> int
//│ Defined type alias Test4

type Test5 = (int -> int) -> int
//│ Defined type alias Test5


type T = int
//│ Defined type alias T

:e
type T = int
type T = int
//│ ╔══[ERROR] Type 'T' is already defined.
//│ ║  l.72: 	type T = int
//│ ╙──      	     ^
//│ ╔══[ERROR] Type 'T' is already defined.
//│ ║  l.73: 	type T = int
//│ ╙──      	     ^

:e
:re
type TypeA = int
foo 42
def foo = 1
foo 42
//│ Defined type alias TypeA
//│ ╔══[ERROR] identifier not found: foo
//│ ║  l.84: 	foo 42
//│ ╙──      	^^^
//│ res: error
//│ Runtime error:
//│   ReferenceError: foo is not defined
//│ foo: 1
//│    = 1
//│ ╔══[ERROR] Type mismatch in application:
//│ ║  l.86: 	foo 42
//│ ║        	^^^^^^
//│ ╟── expression of type `1` is not a function
//│ ║  l.85: 	def foo = 1
//│ ║        	          ^
//│ ╟── but it flows into reference with expected type `42 -> ?a`
//│ ║  l.86: 	foo 42
//│ ╙──      	^^^
//│ res: error
//│ Runtime error:
//│   TypeError: foo is not a function

42: TypeA
//│ res: int
//│    = 42

:e
type TypeOops = TypeOops
type TypeB = TypeC
def test = fun x -> (x: TypeB)
test 42
type TypeC = TypeA
//│ ╔══[ERROR] illegal cycle involving type TypeOops
//│ ║  l.114: 	type TypeOops = TypeOops
//│ ╙──       	     ^^^^^^^^^^^^^^^^^^^
//│ Defined type alias TypeB
//│ Defined type alias TypeC
//│ test: int -> int
//│     = [Function: test]
//│ res: int
//│    = 42



def test = fun (x: TypeB) -> x
//│ test: int -> int
//│     = [Function: test1]



// Note: type alias definitions can contain type variables,
//   which are refreshed on every use (every expansion) of the alias
type Lol = { x: 'a -> 'a }
//│ Defined type alias Lol

:re
error: Lol -> Lol
//│ res: {x: 'a -> 'a} -> {x: 'a0 -> 'a0}
//│ Runtime error:
//│   Error: unexpected runtime error

{ x = id } : Lol
//│ res: {x: 'a -> 'a}
//│    = { x: [Function: id] }


:e
type Runaway[A] = Runaway['a]
//│ ╔══[ERROR] illegal cycle involving type Runaway
//│ ║  l.154: 	type Runaway[A] = Runaway['a]
//│ ╙──       	     ^^^^^^^^^^^^^^^^^^^^^^^^

:e
type Runaway[A] = 'a -> Runaway['a]
//│ ╔══[ERROR] Type definition is not regular: it occurs within itself as Runaway['a], but is defined as Runaway['A]
//│ ║  l.160: 	type Runaway[A] = 'a -> Runaway['a]
//│ ╙──       	     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^


type Runaway2 = Lol -> Runaway2
//│ Defined type alias Runaway2

:e
id: Runaway2
//│ ╔══[ERROR] Type mismatch in type ascription:
//│ ║  l.170: 	id: Runaway2
//│ ║         	^^
//│ ╟── expression of type `{x: ?a -> ?a}` is not a function
//│ ║  l.139: 	type Lol = { x: 'a -> 'a }
//│ ║         	           ^^^^^^^^^^^^^^^
//│ ╟── but it flows into reference of type `?b -> ?b`
//│ ║  l.170: 	id: Runaway2
//│ ║         	^^
//│ ╟── which does not match type `Runaway2`
//│ ╟── Note: constraint arises from function type:
//│ ║  l.166: 	type Runaway2 = Lol -> Runaway2
//│ ║         	                ^^^^^^^^^^^^^^^
//│ ╟── from type reference:
//│ ║  l.170: 	id: Runaway2
//│ ╙──       	    ^^^^^^^^
//│ res: {x: 'a -> 'a} -> 'b as 'b
//│    = [Function: id]

:re
error: Runaway2
//│ res: {x: 'a -> 'a} -> 'b as 'b
//│ Runtime error:
//│   Error: unexpected runtime error

:e
:re
error: {x: int} -> nothing : Runaway2
//│ ╔══[ERROR] Type mismatch in type ascription:
//│ ║  l.198: 	error: {x: int} -> nothing : Runaway2
//│ ║         	^^^^^
//│ ╟── expression of type `?a -> ?a` does not match type `int`
//│ ║  l.139: 	type Lol = { x: 'a -> 'a }
//│ ║         	                ^^^^^^^^
//│ ╟── Note: constraint arises from type reference:
//│ ║  l.198: 	error: {x: int} -> nothing : Runaway2
//│ ╙──       	           ^^^
//│ res: {x: 'a -> 'a} -> 'b as 'b
//│ Runtime error:
//│   Error: unexpected runtime error

:re
error: {x: 'x -> 'x} -> nothing : Runaway2
//│ res: {x: 'a -> 'a} -> 'b as 'b
//│ Runtime error:
//│   Error: unexpected runtime error




type A1[A] = A -> A -> A1[A]
type A2[A] = A -> A2[A]
//│ Defined type alias A1
//│ Defined type alias A2

def ty1: A1[anything]
def ty2: A2[anything]
//│ ty1: anything -> anything -> 'a as 'a
//│ ty2: anything -> 'a as 'a

:re
ty1 = ty2
//│ anything -> 'a as 'a
//│   <:  ty1:
//│ anything -> anything -> 'a as 'a
//│ Runtime error:
//│   ReferenceError: ty2 is not defined

:re
ty2 = ty1
//│ anything -> anything -> 'a as 'a
//│   <:  ty2:
//│ anything -> 'a as 'a
//│ Runtime error:
//│   ReferenceError: ty1 is not defined


